"apiKey"= "AIzaSyAXYIPdSivF8PMCdHQc3mOb61ybZe9Tg9w"
  "authDomain"= "minitravellab.firebaseapp.com"
  "databaseURL"= "https://minitravellab-default-rtdb.firebaseio.com"
  "projectId"= "minitravellab"
  "storageBucket"= "minitravellab.firebasestorage.app"
  "messagingSenderId"= "975780265114"
  "appId"= "1:975780265114:web:0f522562905469397d3323"
  "measurementId"= "G-9QKT0WXHGC"

  
